### ISSUE TITLE
Questions: which method / how many links?

### ISSUE THREAD

**Issue by ghost** [glumb/kinematics#3]
Hi,

happy to see js code about IK :)

some questions:
- which method do you use to compute IK?
- is there a limit on the number of DOF?
- axial joint (I mean the hand rotation related to the forearm, for example): how to define it?

Best,
Al

**Comment by glumb** [comment]
- I use a geometric approach for R0-2 and algebraic for [R3-5](https://github.com/glumb/kinematics/blob/d762c8b029eafea22830a4e3e9a6cc5708633316/src/kinematics.js#L183)
- as you can see on the image in the README, the robots joints have to follow a convention. So it's max 6DOF. You can use the IK to only calculate a 4DOF robot, by only moving in the X-Z plane and therefore not rotating _R3_
- do you refer to _R3_? 

Joints are defined by setting up the geometry array according to the depiction in the readme:

``` js
const geometry = [
      [1,  1,  0], // V0: 1x 1y
      [0, 10,  0], // V1: 10y
      [5,  0,  0], // V2: 5x
      [3,  0,  0], // V3: 3x
      [0, -3,  0], // V4: -3y
    ]
```

_J0_ is always in 0,0,0 (x,y,z). The geometry then tells where each successive joint _J_ is located in relation to the current joint. Therefore, _J1_ is 1,1,0 in relation to _J0_. _J2_ is 0,10,0 in relation to _J1_, but absolute at 1,11,0. And so on.

**Comment by ghost** [comment]
not sure I've understood how to limit to my case, which is 5DOF, but I'll investigate on it.

one more question: any idea on how to put constraints on the angles? in my case each joint has a freedom of pi...3/2pi max, while I imagine your algo expects no constraint.

about URDF: I know it's not difficult to parse it, but if you need to support this format I'll be glad to submit a pull request

**Comment by glumb** [comment]
I don't know how you want to supply the target coordinates to your robot, if you insert a valid pose for your 5DOF robot, _R3_ will be 0, so it is actually limited. You can however not input only x,y,z and let the IK calculate the remaining Euler angles a,b,c.

5DOF is not too complicated, if its all in one plane. Just some geometry.

Constraining must be done with the IKs results. You can just check if the angles are out of your limits and then not move the robot. One thing on the TODOs is to add robot configuration, that means to specify in which "direction" the arm buckles.

I have not yet worked with URDF. I'm not sure if its suited for this IK implementation, since its no general IK, but tied to a very specific robot geometry. Please correct me.

I want this library to be minimal, just IK. I'm writing a robot controller on top of it, having angle constraints, linear interpolation (by calling the IK in small successive steps) and so on.
